/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/treinadora/cliente/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/codigo`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/instrucoes`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/processando`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/protocolos`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/resultado`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/teste`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/transicao`; params?: Router.UnknownInputParams; } | { pathname: `/splash`; params?: Router.UnknownInputParams; } | { pathname: `/treinadora/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/treinadora`; params?: Router.UnknownInputParams; } | { pathname: `/treinadora/login`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/treinadora/cliente/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/cliente/cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `/cliente/codigo`; params?: Router.UnknownOutputParams; } | { pathname: `/cliente/instrucoes`; params?: Router.UnknownOutputParams; } | { pathname: `/cliente/processando`; params?: Router.UnknownOutputParams; } | { pathname: `/cliente/protocolos`; params?: Router.UnknownOutputParams; } | { pathname: `/cliente/resultado`; params?: Router.UnknownOutputParams; } | { pathname: `/cliente/teste`; params?: Router.UnknownOutputParams; } | { pathname: `/cliente/transicao`; params?: Router.UnknownOutputParams; } | { pathname: `/splash`; params?: Router.UnknownOutputParams; } | { pathname: `/treinadora/cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `/treinadora`; params?: Router.UnknownOutputParams; } | { pathname: `/treinadora/login`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/treinadora/cliente/[id]${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/cliente/cadastro${`?${string}` | `#${string}` | ''}` | `/cliente/codigo${`?${string}` | `#${string}` | ''}` | `/cliente/instrucoes${`?${string}` | `#${string}` | ''}` | `/cliente/processando${`?${string}` | `#${string}` | ''}` | `/cliente/protocolos${`?${string}` | `#${string}` | ''}` | `/cliente/resultado${`?${string}` | `#${string}` | ''}` | `/cliente/teste${`?${string}` | `#${string}` | ''}` | `/cliente/transicao${`?${string}` | `#${string}` | ''}` | `/splash${`?${string}` | `#${string}` | ''}` | `/treinadora/cadastro${`?${string}` | `#${string}` | ''}` | `/treinadora${`?${string}` | `#${string}` | ''}` | `/treinadora/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/treinadora/cliente/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/codigo`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/instrucoes`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/processando`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/protocolos`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/resultado`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/teste`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/transicao`; params?: Router.UnknownInputParams; } | { pathname: `/splash`; params?: Router.UnknownInputParams; } | { pathname: `/treinadora/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/treinadora`; params?: Router.UnknownInputParams; } | { pathname: `/treinadora/login`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
